drop table config if exists;  
create table config(  
    id bigint generated by default as identity,  
    cron varchar(40),  
    types number,
    description varchar(200),
    primary key(id)  
);